### ISSUE TITLE
The app crashes after exit

### ISSUE THREAD

**Issue by masudr4n4** [Swati4star/Images-to-PDF#715] opened 2019-04-20 14:09 UTC
<h4>Actual behavior</h4>
The app crashing after double click on back button.
<h4>Expected behavior</h4>
I expected that By double clicking the back button i can successfully  close the app.
<h4>How to reproduce</h4>
<ol>
<li>Download the app from playstore.</li>
<li>Open the apps.</li>
<li>Do anything as your wish</li>
<li>Back to home</li>
<li>Double click on back button on your device.</li>
<li>See the error.</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v8.6.5</li>
<li>OS:Android 6.0.1</li>
<li>Device:Samsung J5</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/aGZeKcmIz98">https://youtu.be/aGZeKcmIz98</a>
<h4> Logcat</h4>
<pre><code>
04-20 18:25:45.138 15989 15989 D AndroidRuntime: Shutting down VM

04-20 18:25:45.138 15989 15989 E AndroidRuntime: FATAL EXCEPTION: main

04-20 18:25:45.138 15989 15989 E AndroidRuntime: Process: swati4star.createpdf, PID: 15989

04-20 18:25:45.138 15989 15989 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {swati4star.createpdf/swati4star.createpdf.activity.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5139)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5162)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:229)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1880)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at swati4star.createpdf.util.FileUtils.makeAndClearTemp(FileUtils.java:454)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at swati4star.createpdf.activity.MainActivity.onDestroy(MainActivity.java:147)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:7130)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1171)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5117)

04-20 18:25:45.138 15989 15989 E AndroidRuntime: 	... 9 more

04-20 18:25:45.148  1647 16115 E android.os.Debug: ro.product_ship = true

04-20 18:25:45.148  1647 16115 E android.os.Debug: ro.debug_level = 0x4f4c

04-20 18:25:45.158  1647 16115 E android.os.Debug: sys.mobilecare.preload = false</code>
</pre>

**Comment by Swati4star** [comment] 2019-04-20 16:05
Thank you for reporting this bug!

**Comment by maaudrana** [comment] 2019-04-20 16:35
you are welcome.
You are really so fast.

**Comment by Ni3verma** [comment] 2019-04-25 05:33
@Swati4star have you checked it? I don't see any error in log

**Comment by Swati4star** [comment] 2019-04-25 05:52
It's not reproducible from my side too. @maaudrana Does this happen every time with your device? or in some specific case?

**Comment by maaudrana** [comment] 2019-04-25 06:32
every time happening this.

**Comment by Swati4star** [comment] 2019-04-27 10:12
Even I am unable to reproduce this.

**Comment by Swati4star** [comment] 2019-10-02 09:30
Fixed in latest build.

**Closed by Swati4star** 2019-10-02 09:30 UTC
Labels: easy, hacktoberfest, up-for-grabs
