### ISSUE TITLE
Enhancement on Application

### ISSUE THREAD

**Issue by yewlimc** [Swati4star/Images-to-PDF#884] opened 2020-01-11 08:46 UTC
I have an interest in enhancing three features in the application: 
1. Add appropriate error messages (fixed in #883)

The left out items:
2. Search functionality inside FAQ
3. Add Chinese translation for Simplified Chinese (Singapore)

**Comment by Swati4star** [comment] 2020-01-11 09:50
The first issue is this one:https://github.com/Swati4star/Images-to-PDF/issues/883

@yewlimc Would you be interested in picking up any of these issue?

**Comment by yash1ts** [comment] 2020-01-22 12:49
I would like to work on the search functionality.

**Comment by Swati4star** [comment] 2020-01-22 12:51
Sure @yash1ts

**Comment by yewlimc** [comment] 2020-01-22 12:52
I am currently working on the search functionality.

**Comment by yash1ts** [comment] 2020-01-22 12:53
ok

**Comment by malbunni** [comment] 2020-04-30 11:45
What kind of improvement you want on the first issue (appropriate error messages)? May you elaborate?

**Comment by Swati4star** [comment] 2020-05-01 05:53
@Diksha2008 First one is already fixed by #883

**Comment by Swati4star** [comment] 2020-05-02 05:57
@yewlimc doesn't seem to be working on this. You can pick this @yash1ts

**Comment by Distin7V** [comment] 2020-05-02 12:20
What other parts that are still left for contribution? Can you point them out please.

**Comment by guicoliv** [comment] 2020-05-07 21:13
Can I work on the search functionality on FAQ? since no one seems to be working on it

**Comment by Swati4star** [comment] 2020-05-08 05:40
Sure @guicoliv

**Comment by vishakha-a** [comment] 2020-05-09 12:31
@guicoliv @Swati4star Is anyone working on the search functionality?

**Comment by guicoliv** [comment] 2020-05-09 13:41
@vishakha-a yes, I'm working on it, it's almost done

**Comment by guicoliv** [comment] 2020-05-09 16:52
@Swati4star I worked with @rubenxcjesus to create a search feature for the FAQ, he will make a pull request in a minute

**Comment by FelipeBonadykov** [comment] 2020-06-16 17:04
Hello! I am beginner in GitHub but with some experience. Could you please point to some issues or tasks to work on?

**Comment by telvinzhong** [comment] 2020-06-17 20:51
I'd be willing to work on the Chinese translations. Could anyone give me pointers for where to do that and how? Also a beginner but happy to learn!

**Comment by Swati4star** [comment] 2020-06-26 17:58
@telvinzhong You can see a similar PR (https://github.com/Swati4star/Images-to-PDF/pull/2). You can check this to add chinese translations

@FelipeBonadykov Please check this project, and if you feel like you can work on any issue, just comment on it. You can create your own issue also. Mail me if you want any further help :)

**Comment by maharishi1** [comment] 2020-07-09 02:06
is Search functionality inside the FAQ issue is still open if yes can I work on it?

**Comment by maharishi1** [comment] 2020-07-11 17:46
Actually I have written the code for this. Could you please tell me can I pull the request?

**Comment by Swati4star** [comment] 2020-07-15 17:37
@maharishi1 You can check any tutorial online. Like, https://opensource.com/article/19/7/create-pull-request-github

**Comment by theekrystallee** [comment] 2020-09-30 23:25
id like to help

**Comment by rashanjyot** [comment] 2020-10-03 14:16
Hi @Swati4star, I'm interested in implementing the Search functionality inside FAQ. Please let me know if it's still open since the thread has been open for quite a while now.

**Comment by Swati4star** [comment] 2020-10-03 18:19
@rashanjyot The issue is open, which means it's not resolved yet.
It's open for you to take up and send PR

cc @theekrystallee

**Comment by Swati4star** [comment] 2020-10-03 18:25
creating a new issue because of too much spam messages here
https://github.com/Swati4star/Images-to-PDF/issues/930
https://github.com/Swati4star/Images-to-PDF/issues/931

Please comment on the issue you want to work on

**Closed by Swati4star** 2020-10-03 18:25 UTC
Labels: good first issue, in progress
