### ISSUE TITLE
Bug in Merge PDF in file selection

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#759] opened 2019-05-15 17:36 UTC
### Steps to reproduce
* Open `Merge PDF`
* Select files using BottomSheet
* Remove Files using `X` icon
* Open Bottom Sheet
* The files which were selected, remain checked 
* Now Uncheck them, They get added in `selected files`

### Expected behaviour
The files which were removed using `X` icon, should be unchecked.

### Actual behaviour
The files which were removed using `X` icon, remain checked.

**Comment by rob729** [comment] 2019-05-16 17:21
@vyankatesh24 I would like to work on this issue.

**Comment by vyankatesh24** [comment] 2019-05-17 10:20
Sure :+1:

**Comment by rob729** [comment] 2019-05-18 17:19
@vyankatesh24 Can you please tell me how to proceed in this issue?
I am not able to find a solution to this issue.

**Comment by vyankatesh24** [comment] 2019-05-19 04:56
Check for selected files in bottom sheet when opened.
Uncheck the ones which are not in selected files.

**Comment by rob729** [comment] 2019-06-07 06:42
@vyankatesh24 please remove the 'in progress' tag as I am not working on this issue.

**Comment by wictors** [comment] 2019-10-13 19:16
Hello. This is my first issue. I would like to try to solve this if it is still open.

**Comment by Swati4star** [comment] 2019-10-14 08:23
Sure @wictors

**Comment by Swati4star** [comment] 2019-10-20 06:41
@wictors Any updates here?

**Comment by wictors** [comment] 2019-10-20 13:19
I have problems. I thought the error was in my devices, but not. I downloaded the current code from GitHub, but I can't run it. There's a error . Check the photo. I cannot run the application via AndroidStudio and debug.

Then I downloaded the application from GooglePlay. It was OK, but the actual behavior is different. I can't reproduce the issue. Check the video. There are different issues.

Some help ? :/

**Link with photos and video :** http://leteckaposta.cz/843572718

**Comment by Swati4star** [comment] 2019-10-20 15:49
@wictors In which locale are you running this app? I am not able to get the exact issue. 
Instead of sending the photo, can you copy paste the logs here?

**Comment by wictors** [comment] 2019-10-21 20:39
I am from Slovakia - Central Europe. 
This is complete logs from app. 

[Issue.txt](https://github.com/Swati4star/Images-to-PDF/files/3752798/Issue.txt)

**Comment by Swati4star** [comment] 2019-10-22 05:26
Please pull the latest code. The crash is now fixed with https://github.com/Swati4star/Images-to-PDF/pull/833

**Comment by Swati4star** [comment] 2019-10-26 10:15
@wictors Are you still facing this issue?
Any updates here?

**Comment by wictors** [comment] 2019-10-27 21:40
Yes. I need a week. Maximum. Then I'll close it with the update.

**Comment by Swati4star** [comment] 2020-07-11 16:06
duplicate of https://github.com/Swati4star/Images-to-PDF/issues/881

**Closed by Swati4star** 2020-07-11 16:06 UTC
Labels: easy, hacktoberfest, up-for-grabs
