### ISSUE TITLE
Add Favourites section on `Home Page` at the top

### ISSUE THREAD

**Issue by Swati4star** [Swati4star/Images-to-PDF#563] opened 2019-02-17 09:37 UTC
- Add a new section on home page - `Favourites`
- It should be empty initially, Just show an icon (or animation) to allow users to add new items there
- When user clicks on the icon, open up a dialog with multiple selectable checkboxes. They should have all the item names that are there on the home page
- The items should then be shown in favourites
- These should be stored in shared prefs

**Comment by jddeep** [comment] 2019-02-26 17:08
@Swati4star i would like to work on this issue please. (Gssoc19) please assign it to me.

**Comment by jddeep** [comment] 2019-03-04 08:34
@Swati4star Can i start working on it now?

**Comment by Swati4star** [comment] 2019-03-04 08:35
Sure. Go ahead 👍

**Comment by jddeep** [comment] 2019-03-04 13:37
@Swati4star I think #582 has broken something the app crashes due to ` IndexOutofBoundsException ` for the ArrayList. I can tell so because the errors oroginate from setNavigationViewSelection methods.

**Comment by jddeep** [comment] 2019-03-04 13:39
@Swati4star to Reproduce : Click on any Card on home page example Add Password, History, etc. many more.

**Comment by vyankatesh24** [comment] 2019-03-04 13:41
@jddeep There is #585 issue for this.

**Comment by Swati4star** [comment] 2019-03-04 13:43
@jddeep If you want, you can work on #585 first. That seems to be a major bug

**Comment by jddeep** [comment] 2019-03-04 13:47
@Swati4star you are right. But that ain't a easy level issue. It needs much time and work.

**Comment by jddeep** [comment] 2019-03-04 13:48
Btw I will be working on it anyway.

**Comment by jddeep** [comment] 2019-03-06 16:42
![screenshot_20190306-221112](https://user-images.githubusercontent.com/43133646/53897749-cc48c200-405c-11e9-9f82-96fa1306b86d.png)
![screenshot_20190306-221112](https://user-images.githubusercontent.com/43133646/53897785-e08cbf00-405c-11e9-9e80-d816db761d49.png)

**Comment by jddeep** [comment] 2019-03-06 16:43
@Swati4star Please tell of this is okay?

**Comment by Swati4star** [comment] 2019-03-06 16:47
This looks good. 💯 
--and what are you going to show on selecting the `+` icon? If you have created that dialog, do share it's screenshot too

**Comment by jddeep** [comment] 2019-03-06 16:55
@Swati4star Am working on it. Will make a PR soon.

**Comment by jddeep** [comment] 2019-03-07 03:49
![screenshot_20190307-091842](https://user-images.githubusercontent.com/43133646/53931173-1b711000-40ba-11e9-8acf-53c64219ef78.png)

**Comment by jddeep** [comment] 2019-03-07 03:50
@Swati4star On clicking the + button this type of Preference Screen appears. Is it cool? And @Swati4star can you provide me a list of Preference options that need to appear? Thanks

**Comment by Swati4star** [comment] 2019-03-07 03:54
@vyankatesh24 @srv-twry can you look into this? I am a bit busy today

Regards,
Swati Garg

**Comment by jddeep** [comment] 2019-03-07 04:54
@vyankatesh24 @srv-twry Please provide a list of preference options that should be there in the pref screen

**Comment by Swati4star** [comment] 2019-03-07 09:49
Looks good. 
Add all the options that are there on the home page. @jddeep

**Comment by jddeep** [comment] 2019-03-07 10:03
@Swati4star Thanks for the response. :)

**Comment by vyankatesh24** [comment] 2019-03-07 10:46
@Swati4star @jddeep Sorry for unavailability.

**Closed** 2019-03-10 12:19 UTC
Labels: gssoc19, hard, in progress
