### ISSUE TITLE
Error Occurred while creating pdf from excel.

### ISSUE THREAD

**Issue by BismeetSingh** [Swati4star/Images-to-PDF#679] opened 2019-04-03 16:08 UTC
Error Occurred while creating pdf from excel.

### Steps to reproduce
Click on Excel to Pdf in the drawer 
Select Excel file from google drive path.
Click excel to pdf and enter pdf name.

### Expected behaviour
Pdf should be generated.

### Actual behaviour
Error message  because file path is null in Excel to pdf fragment if file is selected from drive.

**Comment by vyankatesh24** [comment] 2019-04-03 17:30
This problem arises because we are unable to convert `URI` to `file path` successfully on all devices.
It works on some devices, some devices gives issue.

**Comment by jddeep** [comment] 2019-04-10 06:18
@vyankatesh24 This issue has been resolved as I have updated the RealPathUtil method in the PPT to PDF PR.

**Comment by jddeep** [comment] 2019-04-10 06:19
@Swati4star Once the PPT to PDF PR is merged this issue will get resolved.

**Comment by Swati4star** [comment] 2019-04-10 06:20
okay @jddeep

**Comment by vyankatesh24** [comment] 2019-04-10 07:35
> @Swati4star @vyankatesh24 This issue has been resolved as I have updated the RealPathUtil method in the PPT to PDF PR.

No, I was not able to convert `PPT to PDF` successfully with `Select File` button.
The issue is still present.

**Comment by jddeep** [comment] 2019-04-10 09:08
@vyankatesh24 But you gave screenshots right of converted pdfs?

**Comment by vyankatesh24** [comment] 2019-04-10 09:22
> @vyankatesh24 But you gave screenshots right of converted pdfs?

I tested by directly giving path.

**Comment by jddeep** [comment] 2019-04-10 09:26
Alright if that is the case I will be looking into this as well.

**Comment by jddeep** [comment] 2019-04-10 09:26
@vyankatesh24 Can you please share the paths/URis  which are getting nullified?

**Comment by vyankatesh24** [comment] 2019-04-12 03:57
@BismeetSingh 
Please share the URI which causes error!

**Comment by BismeetSingh** [comment] 2019-04-12 04:35
Uri:
content://com.google.android.apps.docs.storage.legacy/enc%3DO3U_J6b-x3yKQv-1ZOBQqevrYS4k9AuXFST3kWTKiHHpB34YGFYv8J6rSQpbXu2uysEpo5CVrZq8%0ACEYBwSvivW29yPZUXO6jyZjBRt7jI9beQOxF6aboUImcvnzA0tDpayun5g%3D%3D%0A

**Closed** 2019-04-14 11:32 UTC
Labels: bug, gssoc19, in progress, medium
