### ISSUE TITLE
Is there a new version comming to F-Droid soon? 

### ISSUE THREAD

**Issue by 4tip** [Swati4star/Images-to-PDF#871] opened 2019-11-08 11:59 UTC
Hi. 
I wonder if there is a new version comming to F-Droid soon, with more functions and/or improvements? 
The app has not been updated since version 8.5.6, released 2019-01-13.

**Comment by Swati4star** [comment] 2019-11-12 09:48
Duplicate of https://github.com/Swati4star/Images-to-PDF/issues/792

Check https://github.com/Swati4star/Images-to-PDF/issues/792 for communications on this.

**Closed by Swati4star** 2019-11-12 09:48 UTC
