### ISSUE TITLE
Bug in View Files

### ISSUE THREAD

**Issue by vyankatesh24** [Swati4star/Images-to-PDF#747] opened 2019-05-02 03:27 UTC
Bug in the file selection

### Steps to reproduce
* Select Any file 
* Now click `Select All` menu.

### Expected behaviour
All files get selected.

### Actual behaviour
Files get Deselected.

**Comment by archi14** [comment] 2019-05-03 09:12
@vyankatesh24 please assign this to me.

**Comment by Swati4star** [comment] 2019-05-03 10:41
Sure @archi14 (if you have not commented on any other open issue currently)

**Comment by archi14** [comment] 2019-05-09 07:49
Yes working on it.

**Comment by vyankatesh24** [comment] 2019-05-09 12:58
> Yes working on it.

:+1:

**Comment by vyankatesh24** [comment] 2019-05-12 07:46
@archi14 
Any updates?

**Comment by Swati4star** [comment] 2019-05-14 10:21
@archi14 Updates please? the issue is a very small one.
If you are stuck somewhere, let us know.

**Comment by archi14** [comment] 2019-05-15 06:52
@Swati4star Yes, I am stuck,  still trying to find out the solution.

**Comment by vyankatesh24** [comment] 2019-05-17 10:21
@archi14  If you need any help, discuss on the slack channel!

**Comment by archi14** [comment] 2019-05-17 13:27
@vyankatesh24 I am unable to figure out the solution. please assign to someone else.

**Comment by sunnyjain** [comment] 2019-05-17 21:26
Hi, I would like to solve this issue.

**Comment by vyankatesh24** [comment] 2019-05-18 11:36
Sure :+1:

**Closed** 2019-05-21 18:54 UTC
Labels: Beginner, gssoc19, in progress
